// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQdcA5adClPTIoWcL2Ld0gV_NSFI-RTU',
    appId: '1:217338769588:web:059da9475df0b7cfa6a7e1',
    messagingSenderId: '217338769588',
    projectId: 'chatapptute-84474',
    authDomain: 'chatapptute-84474.firebaseapp.com',
    storageBucket: 'chatapptute-84474.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwyZRaxp_73SZjtHq6KdrYsz9BuVZxNI',
    appId: '1:217338769588:android:33a54ae4402ee4b2a6a7e1',
    messagingSenderId: '217338769588',
    projectId: 'chatapptute-84474',
    storageBucket: 'chatapptute-84474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0GIc_b_WXz_JnJdn1Y0q5TcpDbWDcjus',
    appId: '1:217338769588:ios:a2fa84dc3d9d5e43a6a7e1',
    messagingSenderId: '217338769588',
    projectId: 'chatapptute-84474',
    storageBucket: 'chatapptute-84474.appspot.com',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0GIc_b_WXz_JnJdn1Y0q5TcpDbWDcjus',
    appId: '1:217338769588:ios:a2fa84dc3d9d5e43a6a7e1',
    messagingSenderId: '217338769588',
    projectId: 'chatapptute-84474',
    storageBucket: 'chatapptute-84474.appspot.com',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbQdcA5adClPTIoWcL2Ld0gV_NSFI-RTU',
    appId: '1:217338769588:web:ba65c8d526a5f587a6a7e1',
    messagingSenderId: '217338769588',
    projectId: 'chatapptute-84474',
    authDomain: 'chatapptute-84474.firebaseapp.com',
    storageBucket: 'chatapptute-84474.appspot.com',
  );
}
